import LocalizedStrings from "react-localization";
export let consoleDisplayStrings = new LocalizedStrings({
    en: {
        consoleHeader:"Content submitted by the community",
        consoleBack: "Go back",
        consoleOverview: "Overview",
        consoleFilter: "Filter",
        consoleFilterAll: "All",
        consoleCategoryDeleteError: "This category cannot be deleted. There may be recipes linked to it.\nStatus code: ",
        consoleApprove: "Approve",
        consoleApproved: "Approved",
        consoleReject: "Reject",
        consoleRejected: "Rejected",
        consoleFlagged: "Flagged",
        consoleAddFlag: "Flag violation",
        consoleRemoveFlag: "Remove flag",
        consoleFlagMessage: "Flagging note (if any?)",
        consoleConfirmFlag: "Flag this article? The author will be notified.",
        consoleConfirmUnflag: "Unflag this article? The author will be notified.",
        consoleAccountActive: "Active account",
        consoleAccountDisabled: "Account disabled",
        consoleDeactivateAccount: "Deactivate this account",
        consoleReactivateAccount: "Re-activate this account",
        consoleRecipeNav:"Recipes",
        consoleBlogNav:"Blogs",
        consoleVideoNav:"Videos",
        consoleCategoryHeader:"Manage available recipe categories",
        consoleMemberHeader:"Community members",
        consoleMemberNameEmail:"Name & email",
        consoleMemberCountry:"Country",
        consoleMemberRole:"Role",
        consoleMemberAccountStatus:"Account Status",
        consoleMemberLabelUser:"User",
        consoleMemberLabelStatusTrue:"Account is active",
        consoleMemberLabelStatusFalse:"Account is deactivated",
        consoleFlag3day:"Flags in the past 3 days",
        consolePercentFlag:"Flagged rate (%)"
    },
    vi: {
        consoleHeader:"Nội dung từ cộng đồng",
        consoleBack: "Quay lại",
        consoleOverview: "Tổng quan",
        consoleFilter: "Bộ lọc",
        consoleFilterAll: "Tất cả",
        consoleCategoryDeleteError: "Danh mục này không xóa được. Có thể có một số công thức được liên kết với nó.\nMã lỗi: ",
        consoleApprove: "Duyệt",
        consoleApproved: "Đã duyệt",
        consoleReject: "Từ chối",
        consoleRejected: "Đã từ chối",
        consoleFlagged: "Bị cắm cờ",
        consoleAddFlag: "Đặt cờ vi phạm",
        consoleRemoveFlag: "Tháo cờ",
        consoleFlagMessage: "Ghi chú về vi phạm (nếu có?)",
        consoleConfirmFlag: "Đặt cờ bài đăng này? Tác giả sẽ được thông báo về việc này.",
        consoleConfirmUnflag: "Bỏ cờ bài đăng này? Tác giả sẽ được thông báo về việc này.",
        consoleAccountActive: "Tài khoản hiện hoạt",
        consoleAccountDisabled: "Tài khoản không hiện hoạt",
        consoleDeactivateAccount: "Bỏ kích hoạt tài khoản này",
        consoleReactivateAccount: "Kích hoạt lại tài khoản này",
        consoleRecipeNav:"Công thức",
        consoleBlogNav:"Bài viết",
        consoleVideoNav:"Video",
        consoleCategoryHeader:"Quản lý danh mục công thức",
        consoleMemberHeader:"Thành viên",
        consoleMemberNameEmail:"Tên và email",
        consoleMemberCountry:"Quốc gia",
        consoleMemberRole:"Chức vụ",
        consoleMemberAccountStatus:"Trạng thái tài khoản",
        consoleMemberLabelUser:"Thành viên",
        consoleMemberLabelStatusTrue:"Đã kích hoạt",
        consoleMemberLabelStatusFalse:"Chưa kích hoạt",
        consoleFlag3day:"Số cờ từ ba ngày trước",
        consolePercentFlag:"Tỉ lệ cắm cờ (%)"
    }
});