import LocalizedStrings from "react-localization";

export let dashboardDisplayStrings = new LocalizedStrings({
    en: {
        // Common strings
        dashboardEdit: "Edit",
        dashboardViewAll: "View all",
        // Health section
        dashboardHealth: "Your personal index",
        dashboardHealthBmi: "Your BMI is",
        dashboardHealthSuggestMenu: "Let us suggest your menu",
        dashboardHealthCompleteProfile: "Share with us some details about you, so that we may recommend recipes that suit you best",
        dashboardHealthGetStarted: "Get started",
        // Recommendations section
        dashboardRecommendations: "Recommended daily nutrition consumption",
        dashboardRecommendationSubheader: "Based on your BMI, profile and routine.",
        // Recipes section
        dashboardRecipes: "Your recent recipes",
        dashboardRecipesEmpty: "It seems you haven't posted anything yet.",
        // Blogs section
        dashboardBlogs: "Your recent blogs",
        dashboardBlogsEmpty: "It seems you haven't posted anything yet.",
        // Sidebar
        dashboardSidebarMain: "Overview",
        dashboardSidebarMainDashboard: "Dashboard",
        dashboardSidebarMainWeeklyMenu: "Your weekly menu",
        dashboardSidebarMainFavoritePosts: "Your favorite posts",
        dashboardSidebarMainPostHistory: "Your post history",
        dashboardSidebarMainPostDrafts: "Your drafts",
        dashboardSidebarShare: "Something to share?",
        dashboardSidebarShareRecipe: "Share a recipe",
        dashboardSidebarPostVideo: "Share a video",
        dashboardSidebarPostBlog: "Share a story",
        dashboardSidebarSettings: "Tools & settings",
        dashboardSidebarSettingsHealth: "Manage health profile",
        dashboardSidebarSettingsFoodAllergies: "Food abstinence & allergies",
        dashboardSidebarSettingsFoodPreferences: "Food preferences",
        dashboardSidebarSettingsAccount: "Edit account details",
    },
    vi: {
        // Common strings
        dashboardEdit: "Chỉnh sửa",
        dashboardViewAll: "Xem tất cả",
        // Health section
        dashboardHealth: "Thông số cá nhân",
        dashboardHealthBmi: "Chỉ số BMI của bạn là",
        dashboardHealthSuggestMenu: "Đề xuất thực đơn cho bạn",
        dashboardHealthCompleteProfile: "Hãy chia sẻ với chúng tôi một số thông tin để có thể đề xuất các công thức phù hợp hơn với bạn",
        dashboardHealthGetStarted: "Bắt đầu ngay",
        // Recommendations section
        dashboardRecommendations: "Lượng dinh dưỡng bạn cần cho mỗi ngày",
        dashboardRecommendationSubheader: "Dựa vào chỉ số BMI, hồ sơ và thói quen sinh hoạt của bạn.",
        // Recipes section
        dashboardRecipes: "Các công thức gần đây",
        dashboardRecipesEmpty: "Bạn chưa có công thức nào.",
        // Blogs section
        dashboardBlogs: "Các bài viết gần đây",
        dashboardBlogsEmpty: "Bạn chưa có bài viết nào.",
        // Sidebar
        dashboardSidebarMain: "Tổng quan",
        dashboardSidebarMainDashboard: "Trang chính",
        dashboardSidebarMainWeeklyMenu: "Thực đơn của bạn",
        dashboardSidebarMainFavoritePosts: "Các bài đã thích",
        dashboardSidebarMainPostHistory: "Lịch sử đăng bài",
        dashboardSidebarMainPostDrafts: "Bản nháp đã lưu",
        dashboardSidebarShare: "Bạn muốn chia sẻ gì?",
        dashboardSidebarShareRecipe: "Chia sẻ công thức nấu ăn",
        dashboardSidebarPostVideo: "Chia sẻ video hướng dẫn",
        dashboardSidebarPostBlog: "Chia sẻ bài viết",
        dashboardSidebarSettings: "Công cụ và cài đặt",
        dashboardSidebarSettingsHealth: "Quản lý hồ sơ sức khỏe",
        dashboardSidebarSettingsFoodAllergies: "Thực phẩm kiêng cữ & dị ứng",
        dashboardSidebarSettingsFoodPreferences: "Thực phẩm yêu thích",
        dashboardSidebarSettingsAccount: "Chỉnh sửa tài khoản",
    }
})

export let favoritesDisplayStrings = new LocalizedStrings({
    en: {
        favoriteTabsRecipes: "Your favorite recipes",
        favoriteTabsVideos: "Your favorite video",
        favoriteTabsBlogs: "Your favorite blogs",
        favoriteRecipesHeader: "Recipes",
        favoriteRecipesSubheader: "Recipes you added to favorites will be shown here.",
        favoriteVideosHeader: "Videos",
        favoriteVideosSubheader: "Videos you added to favorites will be shown here.",
        favoriteBlogsHeader: "Blogs",
        favoriteBlogsSubheader: "Stories you added to favorites will be shown here.",
    },
    vi: {
        favoriteTabsRecipes: "Công thức yêu thích",
        favoriteTabsVideos: "Video yêu thích",
        favoriteTabsBlogs: "Bài viết yêu thích",
        favoriteRecipesHeader: "Công thức",
        favoriteRecipesSubheader: "Những công thức yêu thích của bạn sẽ được hiển thị ở đây.",
        favoriteVideosHeader: "Video",
        favoriteVideosSubheader: "Những video yêu thích của bạn sẽ được hiển thị ở đây.",
        favoriteBlogsHeader: "Bài viết",
        favoriteBlogsSubheader: "Những bài viết yêu thích của bạn sẽ được hiển thị ở đây.",
    }
})

export let historyDisplayStrings = new LocalizedStrings({
    en: {
        historyTabsRecipes: "Your recipes",
        historyTabsVideos: "Your videos",
        historyTabsBlogs: "Your blogs",
        historyRecipesHeader: "Recipes",
        historyRecipesSubheader: "Your published recipes are shown here.",
        historyRecipesEmpty: "It seems you haven't posted anything yet.",
        historyVideosHeader: "Videos",
        historyVideosSubheader: "Your published videos tutorials.",
        historyVideosEmpty: "It seems you haven't posted anything yet.",
        historyBlogsHeader: "Blogs",
        historyBlogSubheader: "Your published blogs and stories.",
        historyBlogsEmpty: "It seems you haven't posted anything yet.",
    },
    vi: {
        historyTabsRecipes: "Công thức",
        historyTabsVideos: "Video",
        historyTabsBlogs: "Bài viết",
        historyRecipesHeader: "Công thức",
        historyRecipesSubheader: "Công thức mà bạn đã đăng.",
        historyRecipesEmpty: "Có vẻ như bạn chưa đăng công thức nào.",
        historyVideosHeader: "Video",
        historyVideosSubheader: "Video mà bạn đã đăng",
        historyVideosEmpty: "Có vẻ như bạn chưa đăng video nào",
        historyBlogsHeader: "Bài viết",
        historyBlogSubheader: "Bài viết mà bạn đã đăng",
        historyBlogsEmpty: "Có vẻ như bạn chưa đăng bài viết nào",
    }
})

export let draftDisplayStrings = new LocalizedStrings({
    en: {
        draftTabsRecipes: "Recipe drafts",
        draftTabsVideos: "Video drafts",
        draftTabBlogs: "Blog drafts",
        draftRecipesHeader: "Recipes",
        draftRecipesSubheader: "Your saved drafts & private recipes.",
        draftRecipesEmpty: "It seems you haven't saved any drafts yet.",
        draftVideosHeader: "Videos",
        draftVideosSubheader: "Your saved drafts & private videos.",
        draftVideosEmpty: "It seems you haven't saved any drafts yet.",
        draftBlogsHeader: "Blogs",
        draftBlogsSubheader: "Your saved drafts & private blogs.",
        draftBlogsEmpty: "It seems you haven't saved any drafts yet.",
    },
    vi: {
        draftTabsRecipes: "Công thức nháp",
        draftTabsVideos: "Video nháp",
        draftTabBlogs: "Bài viết nháp",
        draftRecipesHeader: "Công thức",
        draftRecipesSubheader: "Nháp và công thức ẩn của bạn.",
        draftRecipesEmpty: "Bạn chưa có bản nháp công thức nào.",
        draftVideosHeader: "Video",
        draftVideosSubheader: "Nháp và video ẩn của bạn.",
        draftVideosEmpty: "Bạn chưa có video tạm nào.",
        draftBlogsHeader: "Bài viết",
        draftBlogsSubheader: "Nháp và bài viết ẩn của bạn.",
        draftBlogsEmpty: "Bạn chưa có bài viết nháp nào.",
    }
})

export let menuDisplayStrings = new LocalizedStrings({
    en: {
        menuHeader: "Menu suggestion",
        menuHeaderNewMenu: "Your new menu",
        menuHeaderSavedMenu: "Showing your saved menu.",
        menuSubheaderProfileIncomplete: "Share with us some details about you, so that we may recommend recipes that suit you best.",
        menuSubheaderEmptyMenu: "Click \"Generate a new menu\" to get started.",
        menuSubheaderNewMenu: "If you like a menu we suggest, save it for later use.",
        menuSubheaderSavedMenuFrom: "Your menu from",
        menuSubheaderSavedMenuTo: "to",
        menuSubheaderExpiredMenu: "This menu has expired, please click \"Generate a new menu\" to get another.",
        menuToday: "Today",
        menuTomorrow: "Tomorrow",
        menuMessageProfileIncomplete: "It seems your health and routine profile are incomplete.",
        menuMessageEmptyMenu: "It seems you don't have a saved menu yet.",
        menuMessageNoRecipes: "Apologies, it seems we couldn't find enough recipes suitable for you... Please check again later.",
        menuUrlCompleteProfile: "Complete your health profile to receive tailored meal plans",
        menuBreakfast: "Breakfast",
        menuLunch: "Lunch",
        menuDinner: "Dinner",
        menuSideDishes: "Side dishes / snacks",
        menuMealNutrients: "Total calories",
        menuSaved: "Menu saved.",
        menuAbout: "About",
        menuDishes: "dishes",
        menuDishAmountLabel: "How many dishes do you want to have per day?",
        menuGenerate: "Generate a new menu",
        menuLoad: "Load your saved menu",
        menuSave: "Save this menu",
        menuCurrentlyShowing: "Showing your saved menu",
        menuAlreadySaved: "Already saved",
    },
    vi: {
        menuHeader: "Đề xuất thực đơn",
        menuHeaderNewMenu: "Thực đơn mới của bạn",
        menuHeaderSavedMenu: "Đang hiện thực đơn bạn đã lưu",
        menuSubheaderProfileIncomplete: "Hãy chia sẻ chúng tôi một chút về bạn để có thể đề xuất thực đơn phù hợp với bạn",
        menuSubheaderEmptyMenu: "Nhấn nút \"Tạo menu mới\" để bắt đầu.",
        menuSubheaderNewMenu: "Nếu bạn thích thực đơn chúng tôi vừa đề xuất, lưu lại để sử dụng sau này.",
        menuSubheaderSavedMenuFrom: "Thực đơn của bạn từ",
        menuSubheaderSavedMenuTo: "đến",
        menuSubheaderExpiredMenu: "Thực đơn này đã quá hạn, xin hãy nhấn nút \"Tạo menu mới\" để lấy thực đơn mới",
        menuToday: "Hôm nay",
        menuTomorrow: "Ngày mai",
        menuMessageProfileIncomplete: "Có vẻ như hồ sơ sức khỏe của bạn chưa hoàn thành",
        menuMessageEmptyMenu: "Có vẻ như bạn chưa có lưu thực đơn nào.",
        menuMessageNoRecipes: "Xin lỗi, có vẻ như chúng tôi không đủ công thức phù hợp với bạn... Vui lòng thử lại sau.",
        menuUrlCompleteProfile: "Hãy hoàn thành hồ sơ sức khỏe ngay để nhận được lịch trình ăn",
        menuBreakfast: "Bữa sáng",
        menuLunch: "Bữa trưa",
        menuDinner: "Bữa tối",
        menuSideDishes: "Món phụ / bữa nhỡ",
        menuMealNutrients: "Tổng calo",
        menuSaved: "Đã lưu thực đơn.",
        menuAbout: "Khoảng",
        menuDishes: "món",
        menuDishAmountLabel: "Bạn muốn ăn bao nhiêu món mỗi ngày?",
        menuGenerate: "Tạo menu mới",
        menuLoad: "Lấy thực đơn đã lưu",
        menuSave: "Lưu thực đơn",
        menuCurrentlyShowing: "Đang hiện thực đơn đã lưu",
        menuAlreadySaved: "Đã lưu",
    }
})

export let profileDisplayStrings = new LocalizedStrings({
    en: {
        profilePictureTab: "Update picture",
        profileDetailsTab: "Update profile",
        profilePasswordTab: "Change password",
        // Update password
        profilePassword: "Change password",
        profilePasswordCurrent: "Your current password",
        profilePasswordCurrentPlaceholder: "Current password",
        profilePasswordNew: "New password",
        profilePasswordNewPlaceholder: "New password",
        profilePasswordConfirmationPlaceholder: "Confirm password",
        profilePasswordIncorrect: "Your old password is incorrect, please try again.",
        profilePasswordNotMatching: "Passwords do not match.",
        profilePasswordTooShort: "Password must be at least 8 characters.",
        profilePasswordMatching: "Passwords match.",
        profilePasswordUpdate: "Update",
        profilePasswordUpdating: "Updating...",
        profilePasswordUpdateSuccess: "Password updated successfully.",
        // Update profile picture
        profilePicture: "Profile picture",
        profilePicturePickerPlaceholder: "Profile picture",
        profilePicturePickerMessage: "Click to pick an image",
        profilePictureClear: "Clear image",
        profilePictureUpdate: "Update",
        profilePictureUpdating: "Updating...",
        profilePictureUpdateSuccess: "Profile image updated.",
        // Update profile details
        profileDetails: "Profile details",
        profileDetailsFirstName: "First name",
        profileDetailsFirstNamePlaceholder: "First name",
        profileDetailsLastName: "Last name",
        profileDetailsLastNamePlaceholder: "Last name",
        profileDetailsEmail: "Email address",
        profileDetailsPhone: "Phone number",
        profileDetailsPhonePlaceholder: "09876...",
        profileDetailsGender: "Gender",
        profileDetailsBirthdate: "Date of birth",
        profileDetailsCountry: "Country",
        profileDetailsFacebook: "Facebook url",
        profileDetailsInstagram: "Instagram url",
        profileDetailsAbout: "About you",
        profileDetailsAboutPlaceholder: "Write a short something about you...",
        profileDetailsUpdate: "Update",
        profileDetailsUpdating: "Updating...",
        profileDetailsUpdateSuccess: "Profile updated.",
    },
    vi: {
        profilePictureTab: "Ảnh đại diện",
        profileDetailsTab: "Hồ sơ",
        profilePasswordTab: "Đổi mật khẩu",
        // Update password
        profilePassword: "Đổi mật khẩu",
        profilePasswordCurrent: "Mật khẩu hiện tại",
        profilePasswordCurrentPlaceholder: "Mật khẩu hiện tại",
        profilePasswordNew: "Mật khẩu mới",
        profilePasswordNewPlaceholder: "Mật khẩu mới",
        profilePasswordConfirmationPlaceholder: "Xác nhận mật khẩu mới",
        profilePasswordIncorrect: "Your old password is incorrect, please try again.",
        profilePasswordNotMatching: "Mật khẩu không khớp.",
        profilePasswordTooShort: "Mật khẩu phải dài ít nhất 8 ký tự.",
        profilePasswordMatching: "Mật khẩu khớp.",
        profilePasswordUpdate: "Cập nhật",
        profilePasswordUpdating: "Đang cập nhật...",
        profilePasswordUpdateSuccess: "Cập nhật mật khẩu thành công.",
        // Update profile picture
        profilePicture: "Hình ảnh hồ sơ",
        profilePicturePickerPlaceholder: "Hình ảnh hồ sơ",
        profilePicturePickerMessage: "Nhấn để chọn hình ảnh",
        profilePictureClear: "Xóa hình ảnh",
        profilePictureUpdate: "Cập nhật",
        profilePictureUpdating: "Đang cập nhật...",
        profilePictureUpdateSuccess: "Cập nhật hình ảnh thành công",
        // Update profile details
        profileDetails: "Chi tiết hồ sơ",
        profileDetailsFirstName: "Tên",
        profileDetailsFirstNamePlaceholder: "Tên",
        profileDetailsLastName: "Họ",
        profileDetailsLastNamePlaceholder: "Họ",
        profileDetailsEmail: "Địa chỉ email",
        profileDetailsPhone: "Số điện thoại",
        profileDetailsPhonePlaceholder: "09876...",
        profileDetailsGender: "Giới tính",
        profileDetailsBirthdate: "Ngày sinh",
        profileDetailsCountry: "Quốc gia",
        profileDetailsFacebook: "Đường dẫn Facebook",
        profileDetailsInstagram: "Đường dẫn Instagram",
        profileDetailsAbout: "Về tôi",
        profileDetailsAboutPlaceholder: "Hãy viết một ít về bạn...",
        profileDetailsUpdate: "Cập nhật",
        profileDetailsUpdating: "Đang cập nhật...",
        profileDetailsUpdateSuccess: "Cập nhật thành công.",
    }
})

export let healthDisplayStrings = new LocalizedStrings({
    en: {
        healthDetailsTab: "Health details",
        healthAllergiesTab: "Food abstinence & allergies",
        healthPreferencesTab: "Food preferences",
        healthAddFoodItem: "Add ingredient",
        healthClearFoodItems: "Clear",
        healthSaveFoodItems: "Save",
        healthFoodItemPlaceholder: "e.g: peppers,...",
        // Update health profile
        healthProfile: "Your health profile & routine",
        healthProfileSubheader: "Share your body stats and workout routine to receive better personalized recipe suggestions.",
        healthProfileBmiMessage: "Your BMI is",
        healthProfileSuggestMenu: "Let us suggest your menu",
        healthProfileIncomplete: "Share with us some details about you, so that we may recommend recipes that suit you best",
        healthProfileEmpty: "Get started",
        healthProfileBmiNone: "We will automatically calculate your BMI with your height and weight.",
        healthProfileSave: "Save",
        healthProfileSaveSuccess: "Health profile updated.",
        // Food abstinence
        foodAbstinence: "Food abstinence & allergies",
        foodAbstinenceSubheader: "Ingredients you abstain from or are allergic to.\nWe will not include recipes with them in our recommendations.",
        foodAbstinenceEmpty: "What are you allergic to, or abstain from?",
        foodAbstinenceUpdateSuccess: "Food abstinence and allergies updated.",
        // Food preferences
        foodPreferences: "Food preferences",
        foodPreferencesSubheader: "Ingredients that you like.\nHelp us recommend more recipes to your tastes!",
        foodPreferencesEmpty: "What's your favorite? Tofu? Cherry tomatoes? Share with us!",
        foodPreferencesUpdateSuccess: "Food preferences updated.",
    },
    vi: {
        healthDetailsTab: "Hồ sơ sức khỏe",
        healthAllergiesTab: "Thực phẩm kiêng cữ & dị ứng",
        healthPreferencesTab: "Thực phẩm yêu thích",
        healthAddFoodItem: "Thêm thực phẩm",
        healthClearFoodItems: "Xóa",
        healthSaveFoodItems: "Lưu",
        healthFoodItemPlaceholder: "ví dụ: tiêu,...",
        // Update health profile
        healthProfile: "Hồ sơ sức khỏe và lịch trình sinh hoạt",
        healthProfileSubheader: "Hãy chia sẻ về chỉ số cơ thể và lịch trình sinh hoạt của bạn để chúng tôi đề xuất các công thức phù hợp",
        healthProfileBmiMessage: "Chỉ số BMI của bạn là",
        healthProfileSuggestMenu: "Đề xuất thực đơn cho bạn",
        healthProfileIncomplete: "Hãy chia sẻ với chúng tôi một số thông tin để có thể đề xuất các công thức phù hợp hơn với bạn",
        healthProfileEmpty: "Bắt đầu ngay",
        healthProfileBmiNone: "Chúng tôi sẽ tính toán chỉ số BMI của bạn dựa trên cân nặng và chiều cao",
        healthProfileSave: "Lưu",
        healthProfileSaveSuccess: "Đã cập nhật hồ sơ sức khỏe.",
        // Food allergies
        foodAbstinence: "Thực phẩm cần kiêng cữ hoặc dị ứng",
        foodAbstinenceSubheader: "Thực phẩm và nguyên liệu mà bạn tránh sử dụng hoặc bị dị ứng.\nChúng tôi sẽ không đề xuất cho bạn những công thức bao gồm các món này.",
        foodAbstinenceEmpty: "Bạn bị dị ứng hay kiêng khem những gì?",
        foodAbstinenceUpdateSuccess: "Đã cập nhật danh sách kiêng cữ & dị ứng.",
        // Food preferences
        foodPreferences: "Thực phẩm yêu thích",
        foodPreferencesSubheader: "Những thực phẩm và nguyên liệu mà bạn thích.\nGiúp chúng tôi đề xuất những công thức phù hợp với khẩu vị của bạn!",
        foodPreferencesEmpty: "Bạn thích ăn gì? Đậu hủ? Cà chua bi? Hãy chia sẻ với chúng tôi!",
        foodPreferencesUpdateSuccess: "Đã cập nhật danh sách thực phẩm yêu thích.",
    }
})

export let postDisplayStrings = new LocalizedStrings({
    en: {
        postSidebarHeader: "Posting as",
        postSidebarProfile: "Your profile",
        postArticleProcessingImages: "Processing image(s)...",
        postArticleUploading: "Uploading your post...",
        postArticleUploadSuccess: "Post uploaded successfully!",
        // Recipes
        postRecipeClear: "Clear",
        postRecipeNextStep: "Next step",
        postRecipePreviousStep: "Previous step",
        postRecipeStep1: "Step 1 - Getting started",
        postRecipeStep1Subheader: "Share with us some details about your new exciting recipe.",
        postRecipeName: "Name your recipe (*)",
        postRecipeNamePlaceholder: "What would you call this dish?",
        postRecipeType: "Recipe type",
        postRecipeDifficulty: "Recipe difficulty",
        postRecipePortion: "Portion",
        postRecipePrepTime: "Prep time (minutes)",
        postRecipeBakingTime: "Baking time (minutes)",
        postRecipeRestingTime: "Resting time (minutes)",
        postRecipeStep2: "Add a picture",
        postRecipeStep2Subheader: "Add a thumbnail to show everyone what your delightful dish would look like.",
        postRecipeThumbnail: "Upload your image and preview it here",
        postRecipeThumbnailPlaceholder: "Click to pick an image...",
        postRecipeStep3: "Step 3 - Add your ingredients",
        postRecipeStep3Subheader: "Add some ingredients and their estimated amounts. Concise and precise ingredient names help us estimate the nutritional values for your recipe better.",
        postRecipeIngredients: "Name an ingredient and its amount (in grams)",
        postRecipeIngredientsEmpty: "Add some ingredients to your recipe...",
        postRecipeIngredientsPlaceholder: "e.g: lettuce, tomato, basil,...",
        postRecipeAddIngredient: "Add ingredient",
        postRecipeStep4: "Step 4 - Add your step-by-step instructions",
        postRecipeStep4Subheader: "Almost there! Share with us the secrets to this recipe and you're done!",
        postRecipeAddStepPlaceholder: "Add some step-by-step guide for your recipe",
        postRecipeAddStep: "Add a step",
        postRecipeSteps: "Step",
        postRecipeStepsPlaceholder: "What to do?",
        postRecipeSaveDraft: "Save draft",
        postRecipeSubmitForReview: "Publish",
        // Videos
        postVideoPreviousStep: "Previous step",
        postVideoStep1: "Step 1 - Getting started",
        postVideoStep1Subheader: "Prefer a more visual approach over walls of text? Share your how-to videos instead!",
        postVideoTitle: "Title (*)",
        postVideoTitlePlaceholder: "Your video title",
        postVideoDescription: "Description",
        postVideoDescriptionPlaceholder: "Your video description",
        postVideoProceed: "Proceed",
        postVideoStep2: "Step 2 - Upload",
        postVideoStep2Subheader: "Pick a video to upload to our server and it's done!",
        postVideoPreview: "Preview",
        postVideoPreviewLink: "Link to your video.",
        postVideoFinish: "Finish",
        postVideoUploading: "Uploading...",
        postVideoUpload: "Upload",
        // Blogs
        postBlog: "Share your story",
        postBlogSubheader: "Please keep content relevant to our site, which is about vegetarian food, recipes and lifestyle.",
        postBlogThumbnail: "Upload a thumbnail for your blog post",
        postBlogThumbnailPlaceholder: "Click to pick an image...",
        postBlogTitle: "Title",
        postBlogSubtitle: "Subtitle (optional)",
        postBlogContent: "What's your story?",
        postBlogClearThumbnail: "Clear thumbnail",
        postBlogSaveDraft: "Save draft",
        postBlogSubmitForReview: "Submit for review",
    },
    vi: {
        postSidebarHeader: "Đăng với tư cách",
        postSidebarProfile: "Hồ sơ của bạn",
        postArticleProcessingImages: "Đang xử lý tập tin...",
        postArticleUploading: "Đang đăng bài viết...",
        postArticleUploadSuccess: "Bài viết đã được đăng thành công!",
        // Recipes
        postRecipeClear: "Xóa",
        postRecipeNextStep: "Bước tiếp theo",
        postRecipePreviousStep: "Bước trước",
        postRecipeStep1: "Bước 1 - Bắt đầu",
        postRecipeStep1Subheader: "Chia sẻ với chúng tôi đôi chút về công thức của bạn",
        postRecipeName: "Tên công thức (*)",
        postRecipeNamePlaceholder: "Bạn sẽ gọi món này là gì?",
        postRecipeType: "Loại",
        postRecipeDifficulty: "Độ khó",
        postRecipePortion: "Khẩu phần ăn",
        postRecipePrepTime: "Thời gian chuẩn bị (phút)",
        postRecipeBakingTime: "Thời gian nướng (phút)",
        postRecipeRestingTime: "Thời gian nghỉ (phút)",
        postRecipeStep2: "Thêm hình ảnh",
        postRecipeStep2Subheader: "Hãy thêm hình ảnh để mọi người có thể thấy món ăn sẽ trong như thế nào.",
        postRecipeThumbnail: "Tải hình ảnh và xem ở đây",
        postRecipeThumbnailPlaceholder: "Nhấn vào để chọn hình ảnh",
        postRecipeStep3: "Bước 3 - Thêm nguyên liệu",
        postRecipeStep3Subheader: "Thêm nguyên liệu vào ước tính số lượng, đặt tên nguyên liệu ngắn gọn và chính xác để chúng tôi ước lượng chỉ số dinh dưỡng cho công thức của bạn",
        postRecipeIngredients: "Thêm nguyên liệu và số lượng (tính theo gam)",
        postRecipeIngredientsEmpty: "Thêm nguyên liệu cho công thức...",
        postRecipeIngredientsPlaceholder: "ví dụ: cải bông, cà chua, húng quế,...",
        postRecipeAddIngredient: "Thêm nguyên liệu",
        postRecipeStep4: "Bước 4 - Thêm chỉ dẫn từng bước để nấu món ăn",
        postRecipeStep4Subheader: "Hãy chia sẻ những bước cho công thức này cho mọi người!",
        postRecipeAddStepPlaceholder: "Thêm chỉ dẫn các bước thực hiện công thức của bạn",
        postRecipeAddStep: "Thêm bước",
        postRecipeSteps: "Bước",
        postRecipeStepsPlaceholder: "Làm gì đây?",
        postRecipeSaveDraft: "Lưu nháp",
        postRecipeSubmitForReview: "Tạo công thức",
        // Videos
        postVideoPreviousStep: "Bước trước",
        postVideoStep1: "Bước 1 - Bắt đầu",
        postVideoStep1Subheader: "Muốn thể hiện rõ hơn thay vì đọc cả một văn bản? Hãy chia sẻ video hướng dẫn ngay!",
        postVideoTitle: "Tiêu đề (*)",
        postVideoTitlePlaceholder: "Tiêu đề của video",
        postVideoDescription: "Mô tả",
        postVideoDescriptionPlaceholder: "Mô tả video",
        postVideoProceed: "Tiếp tục",
        postVideoStep2: "Step 2 - Tải video",
        postVideoStep2Subheader: "Hãy chọn video để tải lên máy chú chúng tôi!",
        postVideoPreview: "Xem trước",
        postVideoPreviewLink: "Đường dẫn đến video của bạn.",
        postVideoFinish: "Xong",
        postVideoUploading: "Đang tải...",
        postVideoUpload: "Tải",
        // Blogs
        postBlog: "Chia sẻ câu chuyện của bạn",
        postBlogSubheader: "Xin hãy giữ nội dụng liên quan về đồ ăn, công thức chay và lối sống của người ăn chay.",
        postBlogThumbnail: "Tải hình ảnh lên cho bài viết của bạn",
        postBlogThumbnailPlaceholder: "Nhấn để chọn hình ảnh...",
        postBlogTitle: "Tiêu đề",
        postBlogSubtitle: "Phụ đề (không bắt buộc)",
        postBlogContent: "Câu chuyện của bạn?",
        postBlogClearThumbnail: "Xóa hình ảnh",
        postBlogSaveDraft: "Lưu nháp",
        postBlogSubmitForReview: "Gửi lên xét duyệt",
    }
})